name: This is an indication that something has been executed or changed

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: windows-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Say confirmation
        run: echo "Something has been run/executed/pushed"
